### ISSUE TITLE
I am unable to pump out of the grindr without taking coal. [1.15.2] 

### ISSUE THREAD

**Issue by mjlmjl888** [noobanidus/grindr#12]
I am using logistical transporters from Mekanism.

**Comment by noobanidus** [comment]
![](https://i.imgur.com/n4p49tW.gif)

This is a standard vanilla behaviour for furnaces, blast furnaces, etc: sides are for fuel extract/insertion (although there is no vanilla method for extracting fuels).

You'll need to attach your logistical transporter to the bottom in order to actually get the output, as though it were a furnace.
